name: 'Esy Override'
description: 'verrides OCaml Dev Version in Esy sandbox'
author: 'Giltho'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  sandbox:
    description: 'A sandbox to override, set to null to use default sandbox'
    default: null
  ocaml-version:
    description: 'An esy-accepted version of OCaml (will override in the sandbox), set to null to keep version of current sandbox.'
    default: null
runs:
  using: 'node12'
  main: 'lib/entrypoint.js'
